name: Go build

on:
#   push:
  workflow_dispatch:

jobs:

  linuxbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: linux Build
      run: |
        #go mod init main
        #go mod tidy
        go build -o fff_linux -v ./
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          fff
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          ./fff_linux
        # The desired behavior if no files are found using the provided path.

  macbuild:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: mac Build
      run: |
        #go mod init main
        #go mod tidy
        go build -o fff_mac -v ./
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          fff
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          ./fff_mac
        # The desired behavior if no files are found using the provided path.

  winbuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Windows Build
      run: |
        #go mod init main
        #go mod tidy
        go build -o fff.exe -v ./
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        # Artifact name
        name: # optional, default is artifact
          fff
        # A file, directory or wildcard pattern that describes what to upload
        path: 
          ./fff.exe
        # The desired behavior if no files are found using the provided path.
